version: '2'
services:
    gitlab:
      image: 'twang2218/gitlab-ce-zh:10.6.4'
      restart: unless-stopped
      hostname: 'gitlab.example.com'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://10.10.20.203'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
      ports:
        - '80:80'
        - '443:443'
        - '8022:22'
      volumes:
        - './data/gitlab/config:/etc/gitlab'
        - './data/gitlab/logs:/var/log/gitlab'
        - './data/gitlab/data:/var/opt/gitlab'
